spring.application.name=SentinelIQ

spring.datasource.url=jdbc:mysql://localhost:3306/sentineliq
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
